# Generated by Django 3.1.3 on 2020-11-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('CourseId', models.IntegerField(primary_key=True, serialize=False)),
                ('CourseTitle', models.CharField(max_length=50)),
                ('CourseName', models.CharField(max_length=50)),
                ('CourseSectionCode', models.IntegerField()),
                ('CourseDepartment', models.CharField(max_length=50)),
                ('InstructorFullName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('StudentId', models.IntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Major', models.CharField(max_length=50)),
                ('Year', models.CharField(max_length=50)),
                ('GPA', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
