# Generated by Django 3.1.3 on 2020-11-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_enroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollmenttable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.IntegerField()),
                ('CourseID', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Enroll',
        ),
    ]
