# Generated by Django 3.1.3 on 2020-11-23 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0004_auto_20201123_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollmenttable',
            old_name='CourseID',
            new_name='IdCourse',
        ),
        migrations.RenameField(
            model_name='enrollmenttable',
            old_name='StudentID',
            new_name='StudentId',
        ),
    ]
